dist: bionic
language: generic
services:
- docker
env:
  global:
  - secure: jA6vk5RGX0bVvHxUAFYReOgdXd8zHV7r5ALHsq3j/Y6EaQbb6ubtT0L71SL1nTIJfP0yWKw3aEoIAF6XfT4tRqtirHfzApZhKbVaNydMVcqyfKCMJHYRWfvFz9VS2t92AmwhyG/aH3YXtMj+3Zh/nJ8jEzPDiCM6SUS5KvuXMoslxtNNCPsTWAx/gVlGfAw6R1kmg4eNHN+f/HohZbfz28fJ4+5ustEkbaguf7ceFQAxt7CLlPzcPFkbrvDGBkSpzIpoJ0Fv01JtjIY1dZhX3mWQfwBlfhcTNpN5XN/DruCz+Z6PB5MSSyCAlqKKD7jLW+7IImZmcXNh8D+dlekQj0c4bKPEiRDxRlrRfSVxQQhfBL51EYjdqAhLPlzGRosUZukSUNuFJyDGs79MY+5t7C4V9m2w/q0bU861Qj3k1l8iuJkG7qu3qK/Yx65t3WSPwVe3bU7klmJFDmldCBcDodxM50PjH94DSdLK+wG4hsKpuvnIWxqvLH689hAbHmzN0NzQP0As7z6nRNTJoHsi/GL+kiqwET2+oKVJG3izO4whxipT1TNs3r8gwzO8rQXiiRf7z4szaWbvkKK5VlwrgIgfWEK03TelU+j7Hr3BiNyLqx+gKg1sH/X+9hNPehT6I1kaudwuA3amCaIeHeAobCWhZ1mzLkQv+miVf1j9oxs=
  - secure: I9/Bz1MHYdPMrko9HBViHP6HI2PM12RAjyxsefbgd3/CGUjpFcSYB4X5JFsIb2grLmhmONe5XN17/PGZUPADGH2BwG7JWHNydsw3QS1bib27783uWEOA7gei1HJ4estcBcw1xi9dacYTdR/tb009DkHW6Nn8akJQ1pIPEAgp5kcbdO7wmk2s4xthCWKx9wtPoVhC4otQfN/lppZ9u1WC13se/akvC/XEUGtEbCsoyOTN4vq+mfPc6YHJq+E8aNkcJWwqdEqhSh+iGs1bZtGYan0LW0yT+cC2EORunMbstyinK71HBLhbYYcHRIGAOgYux3OgeC3XSAlNXyyYY3HIgQUjqnjf6FL04dLQBF9zRNEjo6fYDqoA2xXnShHBdRRO9OgNZz9h+t3owZfxa3Z280zwZuSw8kdMthF4TeYqbqwWDw54sz70Bvkn/LxJzND6sLnmpiSczYlvQcGb8caR68RZVifQPhsoJqJu0QVHAYhpTAGkk7hdSC8/qxQq67mFpu+S05bfh4IwMOBtHBBCCThJCphLxQibMQtO9XPhdEzBJz3zfYc7j4qGq/OLYMgoTROgHp9wjQFZUVOK7cCKDu0nEhEXARjXQLbz/IqkeYlSr57JcSpYHFWty+NFXhBlqTc1d5ZYGOHWxV9oVVVfQXWxVMuLkUu2Dj/eLQsRU9U=

# build image using make
script: make

# release steps
after_success:
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - make release
  - fi
  